#include "LookAndFeel_BlockShuffler.h"

// BinaryData.h is generated at build time by juce_add_binary_data.
// Guard it so the file compiles on a clean checkout before the first cmake run.
#if __has_include(<BinaryData.h>)
  #include <BinaryData.h>
  #define BLOCKSHUFFLER_HAS_BINARY_FONTS 1
#else
  #define BLOCKSHUFFLER_HAS_BINARY_FONTS 0
#endif

namespace BlockShuffler {

LookAndFeel_BlockShuffler::LookAndFeel_BlockShuffler() {
    // Load typefaces from embedded binary data (generated by juce_add_binary_data).
    // Falls back to system fonts if BinaryData.h wasn't generated yet.
#if BLOCKSHUFFLER_HAS_BINARY_FONTS
    interRegular  = juce::Typeface::createSystemTypefaceFor(
                        BinaryData::InterRegular_ttf,
                        BinaryData::InterRegular_ttfSize);
    interBold     = juce::Typeface::createSystemTypefaceFor(
                        BinaryData::InterBold_ttf,
                        BinaryData::InterBold_ttfSize);
    jetbrainsMono = juce::Typeface::createSystemTypefaceFor(
                        BinaryData::JetBrainsMonoRegular_ttf,
                        BinaryData::JetBrainsMonoRegular_ttfSize);
#endif

    // ── Semantic colour IDs ───────────────────────────────────────────────────
    setColour(backgroundBaseId,     juce::Colour(bgDark));
    setColour(backgroundPanelId,    juce::Colour(bgMedium));
    setColour(backgroundElevatedId, juce::Colour(bgLight));
    setColour(backgroundHoverId,    juce::Colour(panelCol));
    setColour(accentId,             juce::Colour(accentCol));
    setColour(accentMutedId,        juce::Colour(accentMuted));
    setColour(textPrimaryId,        juce::Colour(textPrimary));
    setColour(textSecondaryId,      juce::Colour(textSecondary));
    setColour(textTertiaryId,       juce::Colour(textTertiary));
    setColour(borderSubtleId,       juce::Colour(borderSubtle));
    setColour(borderStrongId,       juce::Colour(borderStrong));

    // ── Window / background ───────────────────────────────────────────────────
    setColour(juce::ResizableWindow::backgroundColourId, juce::Colour(bgDark));
    setColour(juce::DocumentWindow::backgroundColourId,  juce::Colour(bgDark));

    // ── Text / labels ─────────────────────────────────────────────────────────
    setColour(juce::Label::textColourId,               juce::Colour(textPrimary));
    setColour(juce::TextEditor::textColourId,           juce::Colour(textPrimary));
    setColour(juce::TextEditor::backgroundColourId,     juce::Colour(bgLight));
    setColour(juce::TextEditor::outlineColourId,        juce::Colour(borderSubtle));
    setColour(juce::TextEditor::highlightColourId,      juce::Colour(accentCol).withAlpha(0.35f));
    setColour(juce::TextEditor::focusedOutlineColourId, juce::Colour(accentCol).withAlpha(0.75f));

    // ── Buttons ───────────────────────────────────────────────────────────────
    setColour(juce::TextButton::buttonColourId,   juce::Colour(bgLight));
    setColour(juce::TextButton::textColourOffId,  juce::Colour(textPrimary));
    setColour(juce::TextButton::buttonOnColourId, juce::Colour(accentCol).withAlpha(0.2f));
    setColour(juce::TextButton::textColourOnId,   juce::Colour(accentCol));

    // ── Sliders ───────────────────────────────────────────────────────────────
    setColour(juce::Slider::thumbColourId,             juce::Colour(accentCol));
    setColour(juce::Slider::trackColourId,             juce::Colour(accentCol).withAlpha(0.4f));
    setColour(juce::Slider::backgroundColourId,        juce::Colour(borderSubtle));
    setColour(juce::Slider::textBoxTextColourId,       juce::Colour(textPrimary));
    setColour(juce::Slider::textBoxBackgroundColourId, juce::Colour(bgLight));
    setColour(juce::Slider::textBoxOutlineColourId,    juce::Colour(borderSubtle));

    // ── Scrollbars ────────────────────────────────────────────────────────────
    setColour(juce::ScrollBar::thumbColourId,      juce::Colour(borderStrong));
    setColour(juce::ScrollBar::backgroundColourId, juce::Colour(bgMedium));

    // ── ComboBox ──────────────────────────────────────────────────────────────
    setColour(juce::ComboBox::backgroundColourId, juce::Colour(bgLight));
    setColour(juce::ComboBox::textColourId,       juce::Colour(textPrimary));
    setColour(juce::ComboBox::outlineColourId,    juce::Colour(borderSubtle));
    setColour(juce::ComboBox::arrowColourId,      juce::Colour(textSecondary));

    // ── PopupMenu ─────────────────────────────────────────────────────────────
    setColour(juce::PopupMenu::backgroundColourId,            juce::Colour(bgMedium));
    setColour(juce::PopupMenu::textColourId,                  juce::Colour(textPrimary));
    setColour(juce::PopupMenu::highlightedBackgroundColourId, juce::Colour(accentCol).withAlpha(0.18f));
    setColour(juce::PopupMenu::highlightedTextColourId,       juce::Colour(accentCol));
    setColour(juce::PopupMenu::headerTextColourId,            juce::Colour(textSecondary));

    // ── ToggleButton / Checkbox ───────────────────────────────────────────────
    setColour(juce::ToggleButton::textColourId,         juce::Colour(textPrimary));
    setColour(juce::ToggleButton::tickColourId,         juce::Colour(accentCol));
    setColour(juce::ToggleButton::tickDisabledColourId, juce::Colour(textTertiary));

    // ── Tooltip ───────────────────────────────────────────────────────────────
    setColour(juce::TooltipWindow::backgroundColourId, juce::Colour(bgLight));
    setColour(juce::TooltipWindow::textColourId,       juce::Colour(textPrimary));
    setColour(juce::TooltipWindow::outlineColourId,    juce::Colour(borderStrong));

}

// ── Font routing ──────────────────────────────────────────────────────────────

juce::Typeface::Ptr LookAndFeel_BlockShuffler::getTypefaceForFont(const juce::Font& f) {
    // Route monospace requests to JetBrains Mono
    if (f.getTypefaceName() == "JetBrainsMono" ||
        f.getTypefaceName() == "Monospace" ||
        f.getTypefaceName() == "Courier New")
        return jetbrainsMono ? jetbrainsMono : LookAndFeel_V4::getTypefaceForFont(f);

    // Bold weight → Inter Bold
    if (f.isBold() || f.getTypefaceName() == "Inter-Bold")
        return interBold ? interBold : LookAndFeel_V4::getTypefaceForFont(f);

    // Default → Inter Regular
    return interRegular ? interRegular : LookAndFeel_V4::getTypefaceForFont(f);
}

juce::Font LookAndFeel_BlockShuffler::uiFont(float size) {
    return juce::Font(juce::FontOptions().withName("Inter").withHeight(size));
}

juce::Font LookAndFeel_BlockShuffler::uiFontBold(float size) {
    return juce::Font(juce::FontOptions().withName("Inter-Bold").withHeight(size).withStyle("Bold"));
}

juce::Font LookAndFeel_BlockShuffler::monoFont(float size) {
    return juce::Font(juce::FontOptions().withName("JetBrainsMono").withHeight(size));
}

// ── Block colour helpers ──────────────────────────────────────────────────────

juce::Array<juce::Colour> LookAndFeel_BlockShuffler::getBlockPalette() {
    return {
        juce::Colour(paletteRed),    // Red
        juce::Colour(paletteOrange), // Orange
        juce::Colour(paletteYellow), // Yellow
        juce::Colour(paletteGreen),  // Green
        juce::Colour(paletteCyan),   // Cyan
        juce::Colour(paletteBlue),   // Blue
        juce::Colour(palettePurple), // Purple
        juce::Colour(palettePink),   // Pink
    };
}

juce::Colour LookAndFeel_BlockShuffler::getBlockColour(int index) {
    auto palette = getBlockPalette();
    if (palette.isEmpty()) return juce::Colour(accentCol);
    return palette[((index % palette.size()) + palette.size()) % palette.size()];
}

// ── drawLinearSlider ──────────────────────────────────────────────────────────

void LookAndFeel_BlockShuffler::drawLinearSlider(juce::Graphics& g,
                                                  int x, int y, int width, int height,
                                                  float sliderPos,
                                                  float /*minSliderPos*/,
                                                  float /*maxSliderPos*/,
                                                  juce::Slider::SliderStyle style,
                                                  juce::Slider& slider)
{
    if (style != juce::Slider::LinearHorizontal && style != juce::Slider::LinearBar) {
        LookAndFeel_V4::drawLinearSlider(g, x, y, width, height, sliderPos,
                                         0.0f, 0.0f, style, slider);
        return;
    }

    const float trackH  = 3.0f;
    const float thumbDia = 12.0f;
    const float thumbR  = thumbDia * 0.5f;
    const float cy      = (float)y + (float)height * 0.5f;
    const float trackX  = (float)x + thumbR;
    const float trackW  = (float)width - thumbDia;
    const float trackY  = cy - trackH * 0.5f;

    // Empty track
    g.setColour(juce::Colour(borderSubtle));
    g.fillRoundedRectangle(trackX, trackY, trackW, trackH, trackH * 0.5f);

    // Filled portion up to thumb
    float fillEnd = sliderPos - thumbR;
    if (fillEnd > trackX) {
        g.setColour(juce::Colour(accentCol));
        g.fillRoundedRectangle(trackX, trackY, fillEnd - trackX, trackH, trackH * 0.5f);
    }

    // Thumb — dark fill + accent ring (2px on hover, 1px otherwise)
    const float thumbX = sliderPos - thumbR;
    const float thumbY = cy - thumbR;
    const float ringW  = slider.isMouseOverOrDragging() ? 2.0f : 1.0f;

    g.setColour(juce::Colour(bgLight));
    g.fillEllipse(thumbX, thumbY, thumbDia, thumbDia);
    g.setColour(juce::Colour(accentCol));
    g.drawEllipse(thumbX + ringW * 0.5f, thumbY + ringW * 0.5f,
                  thumbDia - ringW, thumbDia - ringW, ringW);
}

// ── drawButtonBackground ──────────────────────────────────────────────────────

void LookAndFeel_BlockShuffler::drawButtonBackground(juce::Graphics& g,
                                                      juce::Button& button,
                                                      const juce::Colour& /*backgroundColour*/,
                                                      bool shouldDrawButtonAsHighlighted,
                                                      bool shouldDrawButtonAsDown)
{
    const auto  bounds       = button.getLocalBounds().toFloat().reduced(0.5f);
    const float cornerRadius = 5.0f;
    const bool  isPrimary    = button.getProperties().contains("primary");

    juce::Colour bg, border;
    if (isPrimary) {
        bg = shouldDrawButtonAsDown        ? juce::Colour(accentCol).withAlpha(0.38f)
           : shouldDrawButtonAsHighlighted ? juce::Colour(accentCol).withAlpha(0.26f)
                                           : juce::Colour(accentCol).withAlpha(0.15f);
        border = juce::Colour(accentCol);
    } else {
        bg = shouldDrawButtonAsDown        ? juce::Colour(borderStrong).withAlpha(0.6f)
           : shouldDrawButtonAsHighlighted ? juce::Colour(bgLight).withAlpha(0.55f)
                                           : juce::Colours::transparentBlack;
        border = shouldDrawButtonAsHighlighted ? juce::Colour(borderStrong)
                                               : juce::Colour(borderSubtle);
    }

    // Segmented control: round only the outer corners of the segment group
    auto seg = button.getProperties()["segmentPos"].toString();
    if (seg.isNotEmpty()) {
        bool roundLeft  = (seg == "left");
        bool roundRight = (seg == "right");
        juce::Path path;
        path.addRoundedRectangle(bounds.getX(), bounds.getY(),
                                 bounds.getWidth(), bounds.getHeight(),
                                 cornerRadius, cornerRadius,
                                 roundLeft, roundRight, roundLeft, roundRight);
        g.setColour(bg);
        g.fillPath(path);
        g.setColour(border);
        g.strokePath(path, juce::PathStrokeType(1.0f));
        return;
    }

    g.setColour(bg);
    g.fillRoundedRectangle(bounds, cornerRadius);
    g.setColour(border);
    g.drawRoundedRectangle(bounds, cornerRadius, 1.0f);
}

// ── drawTickBox ───────────────────────────────────────────────────────────────

void LookAndFeel_BlockShuffler::drawTickBox(juce::Graphics& g,
                                             juce::Component& /*component*/,
                                             float x, float y, float w, float h,
                                             bool ticked, bool isEnabled,
                                             bool shouldDrawButtonAsHighlighted,
                                             bool /*shouldDrawButtonAsDown*/)
{
    const float size = juce::jmin(w, h, 16.0f);
    const float bx   = x + (w - size) * 0.5f;
    const float by   = y + (h - size) * 0.5f;
    juce::Rectangle<float> box(bx, by, size, size);

    if (ticked) {
        g.setColour(juce::Colour(accentCol));
        g.fillRoundedRectangle(box, 3.5f);

        // Checkmark path
        juce::Path check;
        const float pad = size * 0.22f;
        check.startNewSubPath(bx + pad,            by + size * 0.54f);
        check.lineTo         (bx + size * 0.42f,   by + size - pad);
        check.lineTo         (bx + size - pad,      by + pad);
        g.setColour(juce::Colours::white);
        g.strokePath(check, juce::PathStrokeType(1.8f, juce::PathStrokeType::curved,
                                                 juce::PathStrokeType::rounded));
    } else {
        if (shouldDrawButtonAsHighlighted) {
            g.setColour(juce::Colour(accentCol).withAlpha(0.10f));
            g.fillRoundedRectangle(box, 3.5f);
        }
        g.setColour(isEnabled ? juce::Colour(borderStrong) : juce::Colour(textTertiary));
        g.drawRoundedRectangle(box.reduced(0.5f), 3.5f, 1.0f);
    }
}

// ── drawTooltip ───────────────────────────────────────────────────────────────

void LookAndFeel_BlockShuffler::drawTooltip(juce::Graphics& g,
                                             const juce::String& text,
                                             int width, int height)
{
    juce::Rectangle<float> bounds(0.5f, 0.5f, (float)width - 1.0f, (float)height - 1.0f);
    g.setColour(juce::Colour(bgLight));
    g.fillRoundedRectangle(bounds, 4.0f);
    g.setColour(juce::Colour(borderStrong));
    g.drawRoundedRectangle(bounds, 4.0f, 1.0f);
    g.setColour(juce::Colour(textPrimary));
    g.setFont(uiFont(11.5f));
    g.drawText(text, juce::Rectangle<int>(8, 4, width - 16, height - 8),
               juce::Justification::centredLeft, true);
}

// ── getTextButtonFont ─────────────────────────────────────────────────────────

juce::Font LookAndFeel_BlockShuffler::getTextButtonFont(juce::TextButton& /*button*/,
                                                         int buttonHeight)
{
    return uiFont(juce::jmin(13.0f, (float)buttonHeight * 0.55f));
}

} // namespace BlockShuffler
