; PlatformIO Project Configuration File
; ESP32 Polyphonic Synthesizer

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DCONFIG_ADC_ENABLE_LEGACY_DRIVER=y
    -DCONFIG_ADC_DISABLE_DAC=n

monitor_speed = 115200
upload_speed = 921600